### ISSUE TITLE
#projects Text-Channel

### ISSUE THREAD

**Issue by RLEXBuilding** [Entwicklertreff/Discord#4]
Hey,
ich fände es toll, wenn es einen Channel gäbe wo man seine Projekte vorstellen kann.

**Comment by Crypti-x** [comment]
Mhm, an sich ne gute Idee, allerdings denke ich das der Server das noch nicht aushält, bzw. noch zu klein ist

**Comment by Crypti-x** [comment]
Öffne diese Issue erneut wenn der Server größer ist ^^
